name: Apptainer build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - '*'
        
env:
  CONTAINER_REGISTRY: joschkabirk
  IMAGE_NAME: pytorch-image

jobs:
  build_latest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.1.2

      - name: Build sif file
        run: apptainer build ${IMAGE_NAME}.sif docker://jobirk/ubuntuplus:latest

      - name: Login to registry
        run: apptainer remote login SylabsCloud -p ${{ secrets.SYSLABS_CONTAINER_REGISTRY }} 

      - name: Push sif file
        run: apptainer push -U ${IMAGE_NAME}.sif library://joschkabirk/pytorch/pytorch-image:latest
