name: Apptainer build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - '*'
        
env:
  CONTAINER_REGISTRY: joschkabirk
  IMAGE_NAME: pytorch-image

jobs:
  build_latest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.1.2
      
      - name: Run an apptainer container
				run: apptainer run docker://alpine cat /etc/os-release          
      - name: Build sif file
        run: apptainer build ${CONTAINER_REGISTRY}/${IMAGE_NAME}.sif docker://${CONTAINER_REGISTRY}/${IMAGE_NAME}:latest
