name: Docker build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - '*'
        
env:
  CONTAINER_REGISTRY: jobirk
  IMAGE_NAME: pytorch-image

jobs:
  build_latest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: docker build -f Dockerfile --tag ${CONTAINER_REGISTRY}/${IMAGE_NAME}:latest .

      # Login and push this image if this is on the main branch

      - name: Login to Dockerhub container registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push ${CONTAINER_REGISTRY}/${IMAGE_NAME}:latest

      - name: Install apptainer
        run: apt update && apt install -y software-properties-common && add-apt-repository -y ppa:apptainer/ppa && apt update && apt install -y apptainer

      - name: Build sif file
        run: apptainer build ${CONTAINER_REGISTRY}/${IMAGE_NAME}.sif docker://${CONTAINER_REGISTRY}/${IMAGE_NAME}:latest
